LUAC = "C:/Program Files (x86)/Gideros/Tools/luac.exe"

all: .tmp/test.lua.bin .tmp/Button.lua.bin .tmp/dataSaver.lua.bin .tmp/easing.lua.bin .tmp/gtween.lua.bin .tmp/json.lua.bin .tmp/Music.lua.bin .tmp/scenemanager.lua.bin .tmp/Sounds.lua.bin .tmp/TextWrap.lua.bin .tmp/LevelScene.lua.bin .tmp/StartScene.lua.bin .tmp/EndScene.lua.bin .tmp/TutorialScene.lua.bin .tmp/SplashartScene.lua.bin .tmp/main.lua.bin .tmp/config.lua.bin .tmp/MainBall.lua.bin .tmp/TouchBall.lua.bin .tmp/dt_healthbar.lua.bin

.tmp/test.lua.bin: test.lua
	$(LUAC) -o ".tmp/test.lua.bin" "test.lua"

.tmp/Button.lua.bin: Button.lua
	$(LUAC) -o ".tmp/Button.lua.bin" "Button.lua"

.tmp/dataSaver.lua.bin: dataSaver.lua
	$(LUAC) -o ".tmp/dataSaver.lua.bin" "dataSaver.lua"

.tmp/easing.lua.bin: easing.lua
	$(LUAC) -o ".tmp/easing.lua.bin" "easing.lua"

.tmp/gtween.lua.bin: gtween.lua
	$(LUAC) -o ".tmp/gtween.lua.bin" "gtween.lua"

.tmp/json.lua.bin: json.lua
	$(LUAC) -o ".tmp/json.lua.bin" "json.lua"

.tmp/Music.lua.bin: Music.lua
	$(LUAC) -o ".tmp/Music.lua.bin" "Music.lua"

.tmp/scenemanager.lua.bin: scenemanager.lua
	$(LUAC) -o ".tmp/scenemanager.lua.bin" "scenemanager.lua"

.tmp/Sounds.lua.bin: Sounds.lua
	$(LUAC) -o ".tmp/Sounds.lua.bin" "Sounds.lua"

.tmp/TextWrap.lua.bin: TextWrap.lua
	$(LUAC) -o ".tmp/TextWrap.lua.bin" "TextWrap.lua"

.tmp/LevelScene.lua.bin: LevelScene.lua
	$(LUAC) -o ".tmp/LevelScene.lua.bin" "LevelScene.lua"

.tmp/StartScene.lua.bin: StartScene.lua
	$(LUAC) -o ".tmp/StartScene.lua.bin" "StartScene.lua"

.tmp/EndScene.lua.bin: EndScene.lua
	$(LUAC) -o ".tmp/EndScene.lua.bin" "EndScene.lua"

.tmp/TutorialScene.lua.bin: TutorialScene.lua
	$(LUAC) -o ".tmp/TutorialScene.lua.bin" "TutorialScene.lua"

.tmp/SplashartScene.lua.bin: SplashartScene.lua
	$(LUAC) -o ".tmp/SplashartScene.lua.bin" "SplashartScene.lua"

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

.tmp/config.lua.bin: config.lua
	$(LUAC) -o ".tmp/config.lua.bin" "config.lua"

.tmp/MainBall.lua.bin: MainBall.lua
	$(LUAC) -o ".tmp/MainBall.lua.bin" "MainBall.lua"

.tmp/TouchBall.lua.bin: TouchBall.lua
	$(LUAC) -o ".tmp/TouchBall.lua.bin" "TouchBall.lua"

.tmp/dt_healthbar.lua.bin: dt_healthbar.lua
	$(LUAC) -o ".tmp/dt_healthbar.lua.bin" "dt_healthbar.lua"

