LUAC = "C:/Program Files (x86)/Gideros/Tools/luac.exe"

all: .tmp/ship.lua.bin .tmp/main.lua.bin .tmp/scenemanager.lua.bin .tmp/TiledMap.lua.bin .tmp/level_1.lua.bin .tmp/level_1_code.lua.bin .tmp/level_2_code.lua.bin .tmp/fire.lua.bin .tmp/boss_1.lua.bin .tmp/gear.lua.bin .tmp/boss_2.lua.bin .tmp/damage.lua.bin .tmp/items.lua.bin .tmp/button.lua.bin .tmp/intro.lua.bin

.tmp/ship.lua.bin: ship.lua
	$(LUAC) -o ".tmp/ship.lua.bin" "ship.lua"

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

.tmp/scenemanager.lua.bin: scenemanager.lua
	$(LUAC) -o ".tmp/scenemanager.lua.bin" "scenemanager.lua"

.tmp/TiledMap.lua.bin: Helper/TiledMap.lua
	$(LUAC) -o ".tmp/TiledMap.lua.bin" "Helper/TiledMap.lua"

.tmp/level_1.lua.bin: Levels/level_1.lua
	$(LUAC) -o ".tmp/level_1.lua.bin" "Levels/level_1.lua"

.tmp/level_1_code.lua.bin: level_1_code.lua
	$(LUAC) -o ".tmp/level_1_code.lua.bin" "level_1_code.lua"

.tmp/level_2_code.lua.bin: level_2_code.lua
	$(LUAC) -o ".tmp/level_2_code.lua.bin" "level_2_code.lua"

.tmp/fire.lua.bin: fire.lua
	$(LUAC) -o ".tmp/fire.lua.bin" "fire.lua"

.tmp/boss_1.lua.bin: boss_1.lua
	$(LUAC) -o ".tmp/boss_1.lua.bin" "boss_1.lua"

.tmp/gear.lua.bin: gear.lua
	$(LUAC) -o ".tmp/gear.lua.bin" "gear.lua"

.tmp/boss_2.lua.bin: boss_2.lua
	$(LUAC) -o ".tmp/boss_2.lua.bin" "boss_2.lua"

.tmp/damage.lua.bin: damage.lua
	$(LUAC) -o ".tmp/damage.lua.bin" "damage.lua"

.tmp/items.lua.bin: items.lua
	$(LUAC) -o ".tmp/items.lua.bin" "items.lua"

.tmp/button.lua.bin: button.lua
	$(LUAC) -o ".tmp/button.lua.bin" "button.lua"

.tmp/intro.lua.bin: intro.lua
	$(LUAC) -o ".tmp/intro.lua.bin" "intro.lua"

